Raises UserError with the message:
The following value caused an error:

123

Raises UserError with the message:
The following value of SampleValueName caused an error:

123

Raises UserError with the message:
The following value of parameter SampleValueName in function SampleFunction caused an error:

123

Raises UserError with the message:
The following value of a parameter in function SampleFunction caused an error:

123

Raises UserError with the message:
The following value of a parameter in method SampleMethod of SampleRecord caused an error:

123

Raises UserError with the message:
The following value of parameter SampleValueName in method SampleMethod of SampleRecord caused an error:

123

